project:
  type: website
  output-dir: docs

website:
  title: "Michael Torby"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - CA-camping.qmd
      - photos.qmd
      - resume.qmd

format:
  html:
    theme:
      light: [minty, styles.css]
      dark: [superhero, dark-styles.css]
    toc: TRUE
    page-layout: full



