project:
  type: website
  output-dir: docs

website:
  title: "Michael Torby"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - CA-camping.qmd
      - photos.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: TRUE
    page-layout: full



